name: Release

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node: [12, 14, 17]
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          registry-url: "https://registry.npmjs.org"

      - name: Run ci
        run: npm ci

  release:
    runs-on: windows-latest
    needs: test
    steps:
      - name: Release
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with: 
          generate_release_notes: true

  publish:
    needs: release
    runs-on: windows-latest
    steps:
      - name: Release and NPM publish
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 17
          registry-url: "https://registry.npmjs.org"

      - id: check
      - uses: EndBug/version-check@v1
        with:
          file-url: https://unpkg.com/console-gui-tools@1.1.12/package.json
          static-checking: localIsNew

      - name: Publish package to NPM 📦
        if: startsWith(github.ref, 'refs/tags/v')
        run: npm publish

        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
